- hosts: all
  gather_facts: False

#  tasks:
#  - name: instala python 2
#    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: wordpress

  roles:
    - server
    - php
    - mysql
    - wordpress
