- hosts: all
  gather_facts: False

#  tasks:
#  - name: instala python 2
#    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    # do the actual apt-get dist-upgrade
  #  - name: apt-get dist-upgrade
  #    apt:
    #    upgrade: dist # upgrade all packages to latest version


- hosts: wordpress

  roles:
    - server
    - php
    - mysql
    - wordpress
