---
- name: Instalação Mysql
  become: yes
  apt:
    name: "{{ item }}"
  with_items:
    - mysql-server
    - python-mysqldb

- name: Inicia Serviço Mysql
  action: service name=mysql state=started


- name: Copia .my.cnf lvl root
  become: true
  become_user: root
  template: src=roles/mysql/templates/.my.cnf dest=/root/.my.cnf owner=root mode=0600


- name: Senha de root
  become: true
  become_user: root
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - localhost

- name: Cria Usuario mysql
  become: true
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "*.*:ALL"

- name: Cria base mysql
  become: true
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present

- name: Deleta anonymous MySQL do $server_hostname
  become: true
  action: mysql_user user="" host="{{ server_hostname }}" state="absent"

- name: Deleta anonymous MySQL do localhost
  become: true
  action: mysql_user user="" state="absent"

- name: Remove  MySQL test database
  become: true
  action: mysql_db db=test state=absent

- name: Update mysql root password todas as contas
  become: true
  mysql_user: name=root host={{ server_hostname }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT
  with_items:
    - "{{ ansible_hostname }}"
    - localhost
