---
- name: Cria mysql database
  mysql_db: name={{ wp_mysql_db }} state=present
  become: yes

- name: Cria mysql user
  mysql_user:
    name={{ wp_mysql_user }}
    password={{ wp_mysql_password }}
    priv=*.*:ALL

  become: yes
